# pods.yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: hellok8s
  labels:
    app: hellok8s
spec:
  containers:
  - name: hellok8s-container
    image: brianstorti/hellok8s:v4

---

apiVersion: v1
kind: Pod
metadata:
  namespace: my-namespace
  name: hellok8s
  labels:
    app: hellok8s
spec:
  containers:
  - name: hellok8s-container
    image: brianstorti/hellok8s:v3

---

apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
spec:
  selector:
    app: hellok8s
  ports:
  - port: 4567
    targetPort: 4567