apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    resources:
      #######################################3
      requests:
        cpu: 500m
        memory: 5Mi
      limits:
        cpu: 500m
        memory: 10Mi

# We can also see a new attribute called resources where we define how much CPU and m

# Request allows pods to use more than the defined cpu
# While Limits don't allow. It restricts

---

apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 200m
    defaultRequest:
      memory: 100Mi
      cpu: 100m
    type: Container


# If we apply this LimitRange to a namespace, every container that it runs that doesn’t define a request and limit will use these default values:





