# hellok8s-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hellok8s-secret
data:
  SECRET_MESSAGE: "SXQgd29ya3Mgd2l0aCBhIFNlY3JldAo="


---

...
        env:
          - name: MESSAGE
            valueFrom:
              secretKeyRef:
                name: hellok8s-secret
                key: SECRET_MESSAGE

---

...
envFrom:
         - secretRef:
             name: hellok8s-secret



---
## stRING daTA
...

apiVersion: v1
kind: Secret
metadata:
  name: hellok8s-secret
stringData:
  SECRET_MESSAGE: "It works with a Secret"

---

kubectl get secret hellok8s-secret -o yaml TO CONVERT ABOVE FILE TO SECRET YAML

